version: "3"
services:
  zookeeper:
    container_name: zookeeper-trt
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka-trt
    image: 'bitnami/kafka:latest'
    ports:
      - '29092:29092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:29092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  # cassandra:
  #     image: bitnami/cassandra:latest
  #     hostname: cassandra
  #     container_name: cassandra
  #     environment:
  #         - CASSANDRA_BROADCAST_ADDRESS=host.docker.internal
  #         - CASSANDRA_CLUSTER_NAME='consulta'
  #     ports:
  #         - "7000:7000"
  #         - "9042:9042"
  #     volumes:
  #         - /path/to/cassandra.yaml:/bitnami/cassandra/conf/cassandra.yaml:ro
  #         - /your/local/path/bitnami/cassandra:/bitnami